# Architecture
arch: ResNet18v

# ===== Dataset ===== #
data: /public/xjy2/ImageProject/data
set: TinyImageNet
name: baseline
num_classes: 200

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256
trainer: amp

# ===== Sparsity =========== #
conv_type: GraphConv2D
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: 1.

# ===== Hardware setup ===== #
workers: 8