# Architecture
arch: cResNet18v

# ===== Dataset ===== #
data: /public/xjy2/ImageProject/data
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr
trainer: amp

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256
trainer: amp

# ===== Sparsity =========== #
conv_type: GraphConv2D
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
first_layer_dense: True
last_layer_dense: True

# ===== Hardware setup ===== #
workers: 4